### ISSUE TITLE
关于dd_kitchen的代码问题

### ISSUE THREAD

**Issue by HenryZhang-git** [CleanDiffuserTeam/CleanDiffuser#39]
您好，当我运行dd_kitchen时出现了这样的报错：
`Traceback (most recent call last):
  File "C:\Users\33908\Desktop\CleanDiffuser1\pipelines\dd_d4rl_kitchen.py", line 34, in pipeline
    env = gym.make(args.task.env_name)
  File "C:\Users\33908\mambaforge\envs\cleandiffuser1\lib\site-packages\gym\envs\registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "C:\Users\33908\mambaforge\envs\cleandiffuser1\lib\site-packages\gym\envs\registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "C:\Users\33908\mambaforge\envs\cleandiffuser1\lib\site-packages\gym\envs\registration.py", line 90, in make
    env = cls(**_kwargs)
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\utils\configurable.py", line 132, in __init__
    base_init(self, *args, **kwargs)
  File "c:\users\33908\d4rl\d4rl\kitchen\kitchen_envs.py", line 39, in __init__
    super(KitchenBase, self).__init__(**kwargs)
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\franka\kitchen_multitask_v0.py", line 181, in __init__
    super(KitchenTaskRelaxV1, self).__init__()
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\utils\configurable.py", line 132, in __init__
    base_init(self, *args, **kwargs)
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\franka\kitchen_multitask_v0.py", line 46, in __init__
    super().__init__(
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\robot_env.py", line 80, in __init__
    super(RobotEnv, self).__init__(
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\mujoco_env.py", line 62, in __init__
    self.sim_robot = MujocoSimRobot(
  File "c:\users\33908\d4rl\d4rl\kitchen\adept_envs\simulation\sim_robot.py", line 61, in __init__
    self.sim = dm_mujoco.Physics.from_xml_path(model_file)
  File "C:\Users\33908\mambaforge\envs\cleandiffuser1\lib\site-packages\dm_control\mujoco\engine.py", line 461, in from_xml_path
    model = wrapper.MjModel.from_xml_path(file_path)
  File "C:\Users\33908\mambaforge\envs\cleandiffuser1\lib\site-packages\dm_control\mujoco\wrapper\core.py", line 306, in from_xml_path
    model_ptr = _get_model_ptr_from_xml(xml_path=xml_path)
  File "C:\Users\33908\mambaforge\envs\cleandiffuser1\lib\site-packages\dm_control\mujoco\wrapper\core.py", line 181, in _get_model_ptr_from_xml
    ptr = mujoco.MjModel.from_xml_path(xml_path, assets or {})
ValueError: XML Error: top-level default class 'main' cannot be renamed
Element 'default', line 0
Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`
我查询了相关报错，是关于xml中main的重复使用，我不知道该如何修改，如果修改了d4rl中kitchen部分的xml，是否会影响我运行kitchen环境下的算法？

**Comment by Josh00-Lu** [comment]
See this PR:
https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/255#issue-2645502926

**Comment by HenryZhang-git** [comment]
> You can refer to this PR: [Farama-Foundation/Gymnasium-Robotics#255 (comment)](https://github.com/Farama-Foundation/Gymnasium-Robotics/pull/255#issue-2645502926)
> 
> or use mujoco version <= 3.1.6.

Thanks, when I make mujoco==3.1.6 and dm_control==1.0.20, the code can be run. 
`pip install dm_control==1.0.20 mujoco==3.1.6`
